# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnets.Attributes')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xPosition', models.FloatField(default=0.0)),
                ('yPosition', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesType',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnets.SpeciesType'),
        ),
        migrations.AddField(
            model_name='speciesattributes',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnets.SpeciesType'),
        ),
        migrations.AddField(
            model_name='bonds',
            name='species1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species1', to='magnets.SpeciesInstance'),
        ),
        migrations.AddField(
            model_name='bonds',
            name='species2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species2', to='magnets.SpeciesInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='speciesinstance',
            unique_together=set([('xPosition', 'yPosition')]),
        ),
        migrations.AlterUniqueTogether(
            name='bonds',
            unique_together=set([('species1', 'species2')]),
        ),
    ]
